"use client";
import {useEffect,useState} from "react";
export default function Page(){
 const [rows,setRows]=useState<any[]>([]),[summary,setSummary]=useState<any>({}),[employees,setEmployees]=useState<any[]>([]),[types,setTypes]=useState<any[]>([]),[status,setStatus]=useState('PENDING'),[edit,setEdit]=useState<any>(null),[msg,setMsg]=useState('');
 async function load(){const [r,e,t]=await Promise.all([fetch('/api/admin/historical-licenses?status='+status),fetch('/api/admin/employees'),fetch('/api/admin/leave-types')]);if(r.ok){const b=await r.json();setRows(b.rows);setSummary(b.summary)}if(e.ok)setEmployees(await e.json());if(t.ok)setTypes(await t.json())}
 useEffect(()=>{load()},[status]);
 async function seed(){const r=await fetch('/api/admin/historical-licenses',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'seed'})});const b=await r.json();setMsg(`PDF registrado: ${b.total||0} páginas · ${b.identified||0} identificadas automáticamente.`);await load()}
 async function save(reject=false){const b=edit;const r=await fetch('/api/admin/historical-licenses',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(reject?{action:'review',id:b.id,status:'REJECTED'}:{action:'review',id:b.id,status:'CONFIRMED',employeeId:b.employee_id,leaveTypeId:b.leave_type_id,articleText:b.article_text,dateFrom:b.date_from,dateTo:b.date_to,quantityValue:b.quantity_value,quantityUnit:b.quantity_unit||'DAYS',sourcePage:b.source_page})});const j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.error||'No se pudo guardar');return}setEdit(null);setMsg(reject?'Página descartada.':'Licencia histórica incorporada.');await load()}
 return <div className="stack"><div><h1 className="heading">Importación histórica 2026</h1><p className="subheading">Revisión controlada del PDF “LICENCIAS 2026-comprimido.pdf”. Ningún registro dudoso se incorpora a licencias sin confirmación administrativa.</p></div>
 <div className="card stack"><div className="form-row"><button className="btn btn-primary" onClick={seed}>Registrar / actualizar PDF histórico</button><button className="btn btn-secondary" onClick={async()=>{const r=await fetch("/api/admin/historical-licenses",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({action:"export-unresolved"})});if(!r.ok){setMsg("No se pudo generar el archivo");return;}const blob=await r.blob();const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download="licencias_2026_pendientes_revision.csv";a.click();URL.revokeObjectURL(u);}}>Descargar pendientes para revisión</button><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="PENDING">Pendientes</option><option value="CONFIRMED">Confirmadas</option><option value="REJECTED">Descartadas</option><option value="ALL">Todas</option></select></div>{msg&&<div className="notice info">{msg}</div>}<div className="form-row"><div className="card"><strong>{summary.total||0}</strong><br/>Páginas registradas</div><div className="card"><strong>{summary.identified||0}</strong><br/>Agente identificado</div><div className="card"><strong>{summary.unmatched||0}</strong><br/>Requieren identificación</div><div className="card"><strong>{summary.confirmed||0}</strong><br/>Licencias confirmadas</div></div></div>
 <div className="card table-wrap"><table><thead><tr><th>Pág.</th><th>Agente</th><th>Confianza</th><th>Artículo</th><th>Desde</th><th>Cantidad</th><th>Estado</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.source_page}</td><td>{r.employee_id?`${r.last_name}, ${r.first_name}`:<span className="badge warn">Sin identificar</span>}</td><td>{r.confidence}</td><td>{r.article_text||'—'}</td><td>{r.date_from||'—'}</td><td>{r.quantity_value?`${r.quantity_value} ${r.quantity_unit==='HOURS'?'horas':'días'}`:'—'}</td><td>{r.status}</td><td>{r.status==='PENDING'&&<button className="btn btn-secondary" onClick={()=>setEdit({...r,leave_type_id:''})}>Revisar</button>}</td></tr>)}</tbody></table></div>
 {edit&&<div className="modal-backdrop"><div className="modal-card stack"><h2 className="heading" style={{fontSize:'1.2rem'}}>Revisar página {edit.source_page}</h2><div className="notice info">{edit.raw_excerpt||'Sin texto OCR suficiente.'}</div><div><label className="label">Agente</label><select className="select" value={edit.employee_id||''} onChange={e=>setEdit({...edit,employee_id:e.target.value})}><option value="">Seleccionar…</option>{employees.map(e=><option key={e.id} value={e.id}>{e.last_name}, {e.first_name} · DNI {e.dni}</option>)}</select></div><div><label className="label">Tipo de licencia</label><select className="select" value={edit.leave_type_id||''} onChange={e=>setEdit({...edit,leave_type_id:e.target.value})}><option value="">Seleccionar…</option>{types.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.article?`${t.article} — `:''}{t.name}</option>)}</select></div><div className="form-row"><div><label className="label">Desde</label><input className="input" type="date" value={edit.date_from||''} onChange={e=>setEdit({...edit,date_from:e.target.value})}/></div><div><label className="label">Hasta</label><input className="input" type="date" value={edit.date_to||''} onChange={e=>setEdit({...edit,date_to:e.target.value})}/></div></div><div className="form-row"><div><label className="label">Cantidad</label><input className="input" type="number" step="0.5" value={edit.quantity_value||''} onChange={e=>setEdit({...edit,quantity_value:e.target.value})}/></div><div><label className="label">Unidad</label><select className="select" value={edit.quantity_unit||'DAYS'} onChange={e=>setEdit({...edit,quantity_unit:e.target.value})}><option value="DAYS">Días</option><option value="HOURS">Horas</option></select></div></div><div className="form-row"><button className="btn btn-primary" onClick={()=>save(false)}>Confirmar e incorporar</button><button className="btn btn-secondary" onClick={()=>save(true)}>Descartar página</button><button className="btn btn-secondary" onClick={()=>setEdit(null)}>Cerrar</button></div></div></div>}</div>
}
