"use client";
import {useEffect,useState} from "react";
export default function Page(){
 const [s,setS]=useState<any>({records:[],byKind:{}}),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false),[filter,setFilter]=useState('ALL');
 async function load(){const r=await fetch('/api/admin/historical-confirmed');if(r.ok)setS(await r.json())}
 useEffect(()=>{load()},[]);
 async function run(){if(!confirm('Se incorporarán únicamente los formularios históricos 2026 validados que se muestran en esta pantalla. No se importan certificados ni documentación respaldatoria. La operación no duplica registros ya incorporados. ¿Continuar?'))return;setLoading(true);setMsg('');const r=await fetch('/api/admin/historical-confirmed',{method:'POST'});const b=await r.json().catch(()=>({}));setLoading(false);if(!r.ok){setMsg(b.error||'No se pudo importar.');return}let t=`Importación finalizada: ${b.imported} nuevos, ${b.already} ya existentes.`;if(b.missingEmployee)t+=` ${b.missingEmployee} no se incorporaron porque el DNI no existe actualmente en Personal.`;setMsg(t);await load()}
 const rows=(s.records||[]).filter((r:any)=>filter==='ALL'||r.kind===filter);
 const kindLabel=(k:string)=>k==='MEDICAL'?'Médica':k==='ADMINISTRATIVE'?'Administrativa':'Vacaciones';
 return <div className="stack"><div><h1 className="heading">Importación histórica 2026</h1><p className="subheading">Carga segura de formularios institucionales revisados. Las actas médicas y solicitudes administrativas confirmadas se incorporan al legajo junto con las vacaciones.</p></div>
 <div className="card stack"><div className="notice info"><strong>Criterio definitivo.</strong> Solo ingresan formularios institucionales con agente y período suficientemente confirmados. Se excluyen certificados, constancias y documentación respaldatoria. Cuando “Hasta” contradice la cantidad, prevalecen <strong>Cantidad + Desde</strong>.</div>
 <div className="grid grid-4"><div className="kpi info"><div className="kpi-label">Total validados</div><div className="kpi-value">{s.validated??'—'}</div></div><div className="kpi info"><div className="kpi-label">Médicas</div><div className="kpi-value">{s.byKind?.MEDICAL??'—'}</div></div><div className="kpi info"><div className="kpi-label">Administrativas</div><div className="kpi-value">{s.byKind?.ADMINISTRATIVE??'—'}</div></div><div className="kpi info"><div className="kpi-label">Vacaciones</div><div className="kpi-value">{s.byKind?.VACATION??'—'}</div></div></div>
 <div className="form-row"><div className="card"><strong>{s.imported??'—'}</strong><br/>Ya incorporados</div><div className="card"><strong>{s.excludedManual??4}</strong><br/>Excluidos para carga manual</div></div>
 <div className="notice warn"><strong>Quedan fuera:</strong> pág. 196, pág. 207 superior, pág. 207 inferior y pág. 209. Se cargarán manualmente cuando estén identificados.</div>
 <button className="btn btn-primary" disabled={loading} onClick={run}>{loading?'Incorporando…':'Incorporar histórico 2026 confirmado'}</button>{msg&&<div className="notice info">{msg}</div>}<p className="subheading">La operación es idempotente: puede ejecutarse nuevamente sin duplicar los formularios ya incorporados.</p></div>
 <div className="card stack"><div className="row"><h2 className="heading" style={{fontSize:'1.15rem',margin:0}}>Registros del lote validado</h2><div className="spacer"/><select className="select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">Todos</option><option value="MEDICAL">Médicas</option><option value="ADMINISTRATIVE">Administrativas</option><option value="VACATION">Vacaciones</option></select></div><div className="table-wrap"><table><thead><tr><th>Pág.</th><th>Clase</th><th>Agente</th><th>DNI</th><th>Artículo</th><th>Desde</th><th>Hasta</th><th>Cantidad</th><th>Observación</th></tr></thead><tbody>{rows.map((r:any)=><tr key={`${r.sourcePage}-${r.formIndex}`}><td>{r.sourcePage}</td><td>{kindLabel(r.kind)}</td><td>{r.employeeName}</td><td>{r.dni}</td><td>{r.sourceArticle}</td><td>{r.dateFrom}</td><td>{r.dateTo}</td><td>{r.quantity} {r.unit==='HOURS'?'h':'días'}</td><td>{r.note||'—'}</td></tr>)}</tbody></table></div></div>
 </div>
}
