import {NextResponse} from "next/server";
import {getAdminSession,canManageLicenses,isGeneralAdmin} from "@/lib/auth";
import {db} from "@/lib/db";
import {ensureV13Schema} from "@/lib/migrations";
import {writeAudit} from "@/lib/audit";
function baseDays(years:number){return years<=5?20:years<=10?25:years<=15?30:35}
function entitlement(years:number,months:number,extra:boolean){const base=baseDays(years);if(months>=6)return base;const units=Math.min(12,Math.max(0,months)+(extra?1:0));return Math.round((base/12*units)*100)/100;}
async function employeeAllowed(sql:any,employeeId:string,s:any){const emp=(await sql`SELECT seniority_date::text,office_id FROM employees WHERE id=${employeeId}`)[0]||null;if(!emp)return {ok:false as const,emp:null,status:404,error:"Agente inexistente"};if(!isGeneralAdmin(s)&&Number(emp.office_id)!==Number(s!.officeId))return {ok:false as const,emp,status:403,error:"No autorizado para este agente"};return {ok:true as const,emp};}
export async function GET(req:Request){
 await ensureV13Schema();const s=await getAdminSession();if(!canManageLicenses(s))return NextResponse.json({error:"No autorizado"},{status:403});const u=new URL(req.url),employeeId=u.searchParams.get("employeeId")||"",year=Number(u.searchParams.get("year"));if(!employeeId||!Number.isInteger(year))return NextResponse.json({error:"Parámetros inválidos"},{status:400});const sql=db();const access=await employeeAllowed(sql,employeeId,s);if(!access.ok)return NextResponse.json({error:access.error},{status:access.status});const emp=access.emp!;
 const p=(await sql`SELECT * FROM vacation_entitlements WHERE employee_id=${employeeId} AND benefit_year=${year}`)[0]||null;let seniorityReference=null as null|number;if(emp?.seniority_date){const d=new Date(emp.seniority_date+'T00:00:00');const cut=new Date(`${year}-12-31T00:00:00`);seniorityReference=Math.max(0,cut.getFullYear()-d.getFullYear()-((cut.getMonth()<d.getMonth()||(cut.getMonth()===d.getMonth()&&cut.getDate()<d.getDate()))?1:0));}const used=(await sql`SELECT COALESCE(SUM(computed_days),0)::int used FROM leave_records WHERE employee_id=${employeeId} AND leave_type='VACATION' AND active=TRUE AND EXTRACT(YEAR FROM date_from)=${year}`)[0];const usedDays=Number(used.used||0),ent=p?Number(p.entitlement_days):null;return NextResponse.json({profile:p,seniorityReference,usedDays,entitlementDays:ent,balance:ent===null?null:Math.round((ent-usedDays)*100)/100,excess:ent===null?null:Math.max(Math.round((usedDays-ent)*100)/100,0)});
}
export async function POST(req:Request){
 await ensureV13Schema();const s=await getAdminSession();if(!canManageLicenses(s))return NextResponse.json({error:"No autorizado"},{status:403});const b=await req.json().catch(()=>({}));const employeeId=String(b.employeeId||""),year=Number(b.year),seniority=Number(b.seniorityYears),months=Number(b.serviceMonths),extra=Boolean(b.extraFractionOver15),notes=String(b.notes||"").slice(0,500);if(!employeeId||!Number.isInteger(year)||year<2020||year>2100||!Number.isInteger(seniority)||seniority<0||seniority>60||!Number.isInteger(months)||months<0||months>12)return NextResponse.json({error:"Datos de vacaciones inválidos"},{status:400});const sql=db();const access=await employeeAllowed(sql,employeeId,s);if(!access.ok)return NextResponse.json({error:access.error},{status:access.status});const days=entitlement(seniority,months,extra);await sql`INSERT INTO vacation_entitlements(employee_id,benefit_year,seniority_years,service_months,extra_fraction_over_15,entitlement_days,notes,updated_by) VALUES(${employeeId},${year},${seniority},${months},${extra},${days},${notes||null},${s!.email}) ON CONFLICT(employee_id,benefit_year) DO UPDATE SET seniority_years=EXCLUDED.seniority_years,service_months=EXCLUDED.service_months,extra_fraction_over_15=EXCLUDED.extra_fraction_over_15,entitlement_days=EXCLUDED.entitlement_days,notes=EXCLUDED.notes,updated_by=EXCLUDED.updated_by,updated_at=now()`;await writeAudit({actor:s!.email,action:"SET_VACATION_ENTITLEMENT",entityType:"vacation_entitlement",entityId:`${employeeId}:${year}`,next:{seniority,months,extra,days}});return NextResponse.json({ok:true,entitlementDays:days});
}
