"use client";
import {FormEvent,useEffect,useState} from "react";

type Permission={code:string;name:string;description?:string};
type Office={id:number;code:string;name:string};
export default function UsuariosPage(){
 const [rows,setRows]=useState<any[]>([]),[catalog,setCatalog]=useState<Permission[]>([]),[offices,setOffices]=useState<Office[]>([]),[msg,setMsg]=useState(""),[form,setForm]=useState({email:"",password:"",officeId:"",permissions:["DASHBOARD","PERSONNEL","LEGAJOS"] as string[],forcePasswordChange:true}),[editing,setEditing]=useState<Record<number,string[]>>({}),[editingOffice,setEditingOffice]=useState<Record<number,string>>({});
 async function load(){const r=await fetch("/api/admin/users");if(r.ok){const b=await r.json();setRows(b.users||[]);setCatalog(b.permissionCatalog||[]);setOffices(b.offices||[]);setEditing(Object.fromEntries((b.users||[]).map((u:any)=>[u.id,u.permissions||[]])));setEditingOffice(Object.fromEntries((b.users||[]).map((u:any)=>[u.id,String(u.office_id||"")])));}else setMsg("No autorizado.");}
 useEffect(()=>{load()},[]);
 function togglePermission(list:string[],code:string){return list.includes(code)?list.filter(x=>x!==code):[...list,code];}
 async function create(e:FormEvent){e.preventDefault();setMsg("");const r=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,officeId:Number(form.officeId)})});const b=await r.json().catch(()=>({}));if(!r.ok){setMsg(b.error||"No se pudo crear");return;}setForm({email:"",password:"",officeId:"",permissions:["DASHBOARD","PERSONNEL","LEGAJOS"],forcePasswordChange:true});setMsg("Usuario creado correctamente.");await load();}
 async function toggle(id:number,active:boolean){const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,active:!active})});const b=await r.json().catch(()=>({}));setMsg(r.ok?(active?"Usuario desactivado.":"Usuario activado."):b.error||"No se pudo actualizar");if(r.ok)load();}
 async function reset(id:number){const pwd=prompt("Ingresá una nueva contraseña temporal (mínimo 8 caracteres):");if(!pwd)return;const forcePasswordChange=confirm("¿Exigir que el usuario cambie esta contraseña temporal en su próximo ingreso?\n\nAceptar = Sí / Cancelar = No");const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,password:pwd,forcePasswordChange})});const b=await r.json().catch(()=>({}));setMsg(r.ok?(forcePasswordChange?"Contraseña temporal asignada. El usuario deberá cambiarla al próximo ingreso.":"Contraseña restablecida."):b.error||"No se pudo restablecer");if(r.ok)load();}
 async function savePermissions(id:number){const permissions=editing[id]||[],officeId=Number(editingOffice[id]);const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,permissions,officeId})});const b=await r.json().catch(()=>({}));setMsg(r.ok?"Permisos y oficina actualizados. Los cambios se aplican inmediatamente.":b.error||"No se pudieron actualizar los permisos");if(r.ok)load();}
 return <div className="stack"><div><h1 className="heading">Usuarios y permisos</h1><p className="subheading">Cada usuario queda vinculado a una oficina y puede acumular varios permisos. El Administrador General mantiene acceso transversal.</p></div>
 <form className="card stack" onSubmit={create}><h2 style={{margin:0}}>Nuevo usuario de oficina</h2><div className="form-row"><div><label className="label">Correo</label><input className="input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="label">Contraseña inicial</label><input className="input" type="password" minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div></div>
 <div><label className="label">Oficina / Dirección</label><select className="input" required value={form.officeId} onChange={e=>setForm({...form,officeId:e.target.value})}><option value="">Seleccionar…</option>{offices.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div>
 <div><label className="label">Permisos</label><div className="stack" style={{gap:8}}>{catalog.map(p=><label key={p.code} className="notice info" style={{display:"flex",gap:10,alignItems:"flex-start",cursor:"pointer"}}><input type="checkbox" checked={form.permissions.includes(p.code)} onChange={()=>setForm({...form,permissions:togglePermission(form.permissions,p.code)})}/><span><strong>{p.name}</strong>{p.description&&<><br/><span>{p.description}</span></>}</span></label>)}</div></div>
 <label className="notice info" style={{display:"flex",gap:10,alignItems:"flex-start",cursor:"pointer"}}><input type="checkbox" checked={form.forcePasswordChange} onChange={e=>setForm({...form,forcePasswordChange:e.target.checked})}/><span><strong>Exigir cambio de contraseña al primer ingreso</strong></span></label>
 {msg&&<div className="notice info">{msg}</div>}<button className="btn btn-primary">Crear usuario</button></form>
 <div className="card table-wrap"><table><thead><tr><th>Correo</th><th>Oficina</th><th>Permisos</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.email}{r.is_general_admin&&<div className="badge good">Administrador General</div>}</td><td>{r.is_general_admin?<strong>Todas</strong>:<select className="input" value={editingOffice[r.id]||""} onChange={e=>setEditingOffice({...editingOffice,[r.id]:e.target.value})}>{offices.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>}</td><td>{r.is_general_admin?<span>Acceso total</span>:<div className="stack" style={{gap:6,minWidth:240}}>{catalog.map(p=><label key={p.code} style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={(editing[r.id]||[]).includes(p.code)} onChange={()=>setEditing({...editing,[r.id]:togglePermission(editing[r.id]||[],p.code)})}/><span>{p.name}</span></label>)}<button className="btn btn-secondary" onClick={()=>savePermissions(r.id)}>Guardar acceso</button></div>}</td><td>{r.active?"Activo":"Inactivo"}{r.must_change_password&&<div className="muted">Cambio de contraseña pendiente</div>}</td><td><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="btn btn-secondary" onClick={()=>reset(r.id)}>Restablecer contraseña</button><button className="btn btn-secondary" onClick={()=>toggle(r.id,r.active)}>{r.active?"Desactivar":"Activar"}</button></div></td></tr>)}</tbody></table></div></div>;
}
