"use client";
import {FormEvent,useEffect,useState} from "react";
export default function UsuariosPage(){
 const [rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState(""),[form,setForm]=useState({email:"",password:"",role:"LICENSE_OPERATOR"});
 async function load(){const r=await fetch("/api/admin/users");if(r.ok)setRows(await r.json());else setMsg("No autorizado.");}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();setMsg("");const r=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const b=await r.json().catch(()=>({}));if(!r.ok){setMsg(b.error||"No se pudo crear");return;}setForm({email:"",password:"",role:"LICENSE_OPERATOR"});setMsg("Usuario creado correctamente.");await load();}
 async function toggle(id:number,active:boolean){const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,active:!active})});if(r.ok)load();}
 async function reset(id:number){const pwd=prompt("Ingresá una nueva contraseña temporal (mínimo 8 caracteres):");if(!pwd)return;const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,password:pwd})});const b=await r.json().catch(()=>({}));setMsg(r.ok?"Contraseña restablecida.":b.error||"No se pudo restablecer");}
 return <div className="stack"><div><h1 className="heading">Usuarios y permisos</h1><p className="subheading">Creá accesos restringidos sin compartir la cuenta administradora.</p></div>
 <form className="card stack" onSubmit={create}><h2 style={{margin:0}}>Nuevo usuario</h2><div className="form-row"><div><label className="label">Correo</label><input className="input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="label">Contraseña inicial</label><input className="input" type="password" minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div></div><div><label className="label">Rol</label><select className="select" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="LICENSE_OPERATOR">Operador de Licencias</option><option value="ADMIN">Administrador</option></select></div><div className="notice info"><strong>Operador de Licencias:</strong> puede buscar agentes, registrar/consultar licencias y vacaciones y ver saldos. No puede modificar personal, horarios, QR, dispositivos, asistencia, configuración ni usuarios.</div>{msg&&<div className="notice info">{msg}</div>}<button className="btn btn-primary">Crear usuario</button></form>
 <div className="card table-wrap"><table><thead><tr><th>Correo</th><th>Rol</th><th>Estado</th><th>Último acceso</th><th>Acciones</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.email}</td><td>{r.role==="LICENSE_OPERATOR"?"Operador de Licencias":"Administrador"}</td><td>{r.active?"Activo":"Inactivo"}</td><td>{r.last_login_at?new Date(r.last_login_at).toLocaleString("es-AR"):"—"}</td><td><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="btn btn-secondary" onClick={()=>reset(r.id)}>Reset contraseña</button><button className="btn btn-secondary" onClick={()=>toggle(r.id,r.active)}>{r.active?"Desactivar":"Activar"}</button></div></td></tr>)}</tbody></table></div></div>;
}
