"use client";
import {useEffect,useMemo,useState} from "react";

type Row={id:string;last_name:string;first_name:string;dni:string;employment:string;office_name:string;scheduled_days:number;total_absences:number;justified:number;unjustified:number;late_entries:number;effective_late:number;late_minutes:number;compensated_minutes:number;late_pending_minutes:number;pending_minutes:number};
type Movement={id?:number|string;event_type:string;time:string};
function localDate(){const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`}
function currentMonthValue(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function yearStart(){return `${new Date().getFullYear()}-01-01`}
function fmtDate(v:string){return v?`${v.slice(8,10)}/${v.slice(5,7)}/${v.slice(0,4)}`:"—"}
function fmtDay(v:string){if(!v)return "—";const [y,m,d]=v.split("-").map(Number);return new Intl.DateTimeFormat("es-AR",{weekday:"long",timeZone:"UTC"}).format(new Date(Date.UTC(y,m-1,d))).replace(/^./,x=>x.toUpperCase())}
function esc(v:any){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function monthRange(value:string){const [y,m]=value.split("-").map(Number);if(!y||!m)return {from:yearStart(),to:localDate()};const last=new Date(y,m,0).getDate();const start=`${y}-${String(m).padStart(2,"0")}-01`;let end=`${y}-${String(m).padStart(2,"0")}-${String(last).padStart(2,"0")}`;const today=localDate();if(start<=today&&end>today)end=today;return {from:start,to:end}}
function monthTitle(value:string){const [y,m]=value.split("-").map(Number);if(!y||!m)return value;const label=new Intl.DateTimeFormat("es-AR",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(y,m-1,1)));return label.replace(/^./,x=>x.toUpperCase())}
function statusLabel(s:string){return s==="PRESENT"?"Presente":s==="JUSTIFIED"?"Justificada":s==="ABSENT"?"Sin justificar":"Pendiente"}
function movementParts(a:any){
  const movements:Array<Movement>=Array.isArray(a?.movements)?a.movements:[];
  const entry=movements.find(m=>m.event_type==="ENTRY")?.time||a?.entry_local||"—";
  const reentries=movements.filter(m=>m.event_type==="REENTRY").map(m=>m.time);
  const exits=movements.map((m,i)=>({m,i})).filter(x=>x.m.event_type==="EXIT"||x.m.event_type==="AUTO_EXIT");
  const intermediate:string[]=[];let finalExit="—";
  exits.forEach(({m,i})=>{const hasLaterReentry=movements.slice(i+1).some(x=>x.event_type==="REENTRY");if(hasLaterReentry)intermediate.push(m.time);else finalExit=m.time;});
  if(finalExit==="—"&&a?.exit_local&&!intermediate.includes(a.exit_local))finalExit=a.exit_local;
  return {entry,intermediate:intermediate.length?intermediate.join(" · "):"—",reentries:reentries.length?reentries.join(" · "):"—",finalExit};
}
function Kpi({label,value}:{label:string;value:any}){return <div className="kpi info"><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div></div>}

export default function ReportesPage(){
  const [from,setFrom]=useState(yearStart()),[to,setTo]=useState(localDate()),[officeId,setOfficeId]=useState(""),[rows,setRows]=useState<Row[]>([]),[offices,setOffices]=useState<any[]>([]),[scopeName,setScopeName]=useState(""),[q,setQ]=useState(""),[employeeId,setEmployeeId]=useState(""),[detail,setDetail]=useState<any>(null),[loading,setLoading]=useState(false),[msg,setMsg]=useState("");
  const [monthlyMonth,setMonthlyMonth]=useState(currentMonthValue()),[monthlyEmployeeId,setMonthlyEmployeeId]=useState("");
  async function load(range?:{from:string;to:string}){setLoading(true);setMsg("");const rf=range?.from||from,rt=range?.to||to;const qs=new URLSearchParams({from:rf,to:rt});if(officeId)qs.set("officeId",officeId);const r=await fetch(`/api/admin/employee-summary?${qs.toString()}`,{cache:"no-store"});const b=await r.json().catch(()=>({}));if(r.ok){setRows(b.rows||[]);setOffices(b.offices||[]);setScopeName(b.officeName||"");if(employeeId&&!b.rows?.some((x:any)=>String(x.id)===String(employeeId))){setEmployeeId("");setDetail(null)}}else setMsg(b.error||"No se pudo generar el reporte");setLoading(false)}
  useEffect(()=>{load()},[]);
  async function fetchDetail(id:string,rf=from,rt=to){const r=await fetch(`/api/admin/employee-file?employeeId=${encodeURIComponent(id)}&from=${rf}&to=${rt}`,{cache:"no-store"});const b=await r.json().catch(()=>({}));if(r.ok){setDetail(b);return b}else{setMsg(b.error||"No se pudo cargar el detalle del agente");return null}}
  async function loadDetail(id:string){setEmployeeId(id);if(!id){setDetail(null);return}await fetchDetail(id)}
  async function generateMonthly(){if(!monthlyEmployeeId){setMsg("Seleccioná un agente para generar el reporte mensual.");return}setMsg("");const range=monthRange(monthlyMonth);setFrom(range.from);setTo(range.to);setEmployeeId(monthlyEmployeeId);await Promise.all([load(range),fetchDetail(monthlyEmployeeId,range.from,range.to)]);setTimeout(()=>document.getElementById("reporte-mensual-individual")?.scrollIntoView({behavior:"smooth",block:"start"}),50)}
  const filtered=useMemo(()=>rows.filter(r=>`${r.last_name} ${r.first_name} ${r.dni} ${r.office_name}`.toLowerCase().includes(q.trim().toLowerCase())),[rows,q]);
  const monthlyOptions=useMemo(()=>rows.filter(r=>!officeId||true).sort((a,b)=>`${a.last_name} ${a.first_name}`.localeCompare(`${b.last_name} ${b.first_name}`,"es")),[rows,officeId]);
  const totals=useMemo(()=>filtered.reduce((a,r)=>({people:a.people+1,abs:a.abs+Number(r.total_absences||0),just:a.just+Number(r.justified||0),unjust:a.unjust+Number(r.unjustified||0),late:a.late+Number(r.late_entries||0),pending:a.pending+Number(r.late_pending_minutes||0)}),{people:0,abs:0,just:0,unjust:0,late:0,pending:0}),[filtered]);
  function currentMonth(){const range=monthRange(currentMonthValue());setMonthlyMonth(currentMonthValue());setFrom(range.from);setTo(range.to)}
  function currentYear(){setFrom(yearStart());setTo(localDate())}
  function exportExcel(){
    const title=`Reporte de asistencia ${fmtDate(from)} al ${fmtDate(to)}`;
    const body=filtered.map(r=>`<tr><td>${esc(r.office_name)}</td><td>${esc(`${r.last_name}, ${r.first_name}`)}</td><td>${esc(r.dni)}</td><td>${r.scheduled_days}</td><td>${r.total_absences}</td><td>${r.justified}</td><td>${r.unjustified}</td><td>${r.late_entries}</td><td>${r.late_minutes}</td><td>${r.compensated_minutes}</td><td>${r.late_pending_minutes}</td></tr>`).join("");
    const html=`<html><head><meta charset="utf-8"></head><body><h2>${esc(title)}</h2><table border="1"><thead><tr><th>Oficina</th><th>Agente</th><th>DNI</th><th>Días previstos</th><th>Faltas totales</th><th>Justificadas</th><th>Injustificadas</th><th>Tardanzas</th><th>Minutos atraso</th><th>Minutos compensados</th><th>Minutos pendientes</th></tr></thead><tbody>${body}</tbody></table></body></html>`;
    const blob=new Blob(["\ufeff",html],{type:"application/vnd.ms-excel;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`reporte_asistencia_${from}_${to}.xls`;a.click();URL.revokeObjectURL(a.href);
  }
  function exportIndividual(){if(!detail)return;const e=detail.employee;const body=(detail.attendance||[]).map((a:any)=>{const p=movementParts(a);return `<tr><td>${esc(fmtDate(a.work_date))}</td><td>${esc(fmtDay(a.work_date))}</td><td>${esc(`${a.scheduled_start||"—"}–${a.scheduled_end||"—"}`)}</td><td>${esc(p.entry)}</td><td>${esc(p.intermediate)}</td><td>${esc(p.reentries)}</td><td>${esc(p.finalExit)}</td><td>${esc(statusLabel(a.status))}</td><td>${Number(a.late_minutes||0)}</td><td>${Number(a.compensation_minutes||0)}</td><td>${Math.max(0,Number(a.late_minutes||0)-Number(a.compensation_minutes||0))}</td><td>${esc((a.type_name||a.leave_type||"—")+(a.article?` · ${a.article}`:""))}</td></tr>`}).join("");
    const title=`Reporte mensual individual · ${e.last_name}, ${e.first_name}`;const subtitle=`DNI ${e.dni} · ${fmtDate(from)} al ${fmtDate(to)}`;
    const html=`<html><head><meta charset="utf-8"></head><body><h2>${esc(title)}</h2><p>${esc(subtitle)}</p><p><b>Presentes:</b> ${detail.summary.present||0} &nbsp; <b>Justificadas:</b> ${detail.summary.justified||0} &nbsp; <b>Injustificadas:</b> ${detail.summary.absent||0} &nbsp; <b>Tardanzas:</b> ${detail.summary.lateEntries||0} &nbsp; <b>Min. a compensar:</b> ${(detail.attendance||[]).reduce((s:number,a:any)=>s+Math.max(0,Number(a.late_minutes||0)-Number(a.compensation_minutes||0)),0)}</p><table border="1"><thead><tr><th>Fecha</th><th>Día</th><th>Horario previsto</th><th>Entrada</th><th>Salidas intermedias</th><th>Reingresos</th><th>Salida final</th><th>Estado</th><th>Atraso</th><th>Compensado</th><th>A compensar</th><th>Justificación</th></tr></thead><tbody>${body}</tbody></table></body></html>`;
    const blob=new Blob(["\ufeff",html],{type:"application/vnd.ms-excel;charset=utf-8"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`reporte_mensual_${String(e.dni||"agente").replace(/\D/g,"")}_${from.slice(0,7)}.xls`;link.click();URL.revokeObjectURL(link.href);
  }
  function printIndividual(){if(!detail)return;const e=detail.employee;const rowsHtml=(detail.attendance||[]).map((a:any)=>{const p=movementParts(a);return `<tr><td>${esc(fmtDate(a.work_date))}</td><td>${esc(fmtDay(a.work_date))}</td><td>${esc(`${a.scheduled_start||"—"}–${a.scheduled_end||"—"}`)}</td><td>${esc(p.entry)}</td><td>${esc(p.intermediate)}</td><td>${esc(p.reentries)}</td><td>${esc(p.finalExit)}</td><td>${esc(statusLabel(a.status))}</td><td>${Number(a.late_minutes||0)} min</td><td>${Math.max(0,Number(a.late_minutes||0)-Number(a.compensation_minutes||0))} min</td><td>${esc((a.type_name||a.leave_type||"—")+(a.article?` · ${a.article}`:""))}</td></tr>`}).join("");const pending=(detail.attendance||[]).reduce((s:number,a:any)=>s+Math.max(0,Number(a.late_minutes||0)-Number(a.compensation_minutes||0)),0);
    const w=window.open("","_blank","width=1200,height=800");if(!w){setMsg("El navegador bloqueó la ventana de impresión. Habilitá ventanas emergentes para este sitio.");return}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Reporte mensual individual</title><style>body{font-family:Arial,sans-serif;color:#17212b;margin:28px}h1{font-size:20px;margin:0 0 4px}h2{font-size:16px;margin:18px 0 8px}.muted{color:#5c6875}.summary{display:flex;gap:12px;flex-wrap:wrap;margin:18px 0}.box{border:1px solid #cfd7df;border-radius:6px;padding:8px 12px}.box b{display:block;font-size:18px}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #ccd4dc;padding:5px 4px;vertical-align:top}th{background:#f1f4f7}@media print{body{margin:10mm}@page{size:A4 landscape;margin:8mm}}</style></head><body><div>GOBIERNO DE CORRIENTES · MINISTERIO DE EDUCACIÓN</div><h1>Reporte mensual individual de entradas y salidas</h1><div class="muted">${esc(`${e.last_name}, ${e.first_name}`)} · DNI ${esc(e.dni)} · ${esc(fmtDate(from))} al ${esc(fmtDate(to))}</div><div class="summary"><div class="box">Presentes<b>${detail.summary.present||0}</b></div><div class="box">Justificadas<b>${detail.summary.justified||0}</b></div><div class="box">Injustificadas<b>${detail.summary.absent||0}</b></div><div class="box">Tardanzas<b>${detail.summary.lateEntries||0}</b></div><div class="box">Min. a compensar<b>${pending}</b></div></div><table><thead><tr><th>Fecha</th><th>Día</th><th>Horario</th><th>Entrada</th><th>Salidas intermedias</th><th>Reingresos</th><th>Salida final</th><th>Estado</th><th>Atraso</th><th>A compensar</th><th>Justificación</th></tr></thead><tbody>${rowsHtml}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close();
  }
  const detailPending=detail?(detail.attendance||[]).reduce((s:number,a:any)=>s+Math.max(0,Number(a.late_minutes||0)-Number(a.compensation_minutes||0)),0):0;
  return <div className="stack report-page">
    <div><h1 className="heading">Reportes de asistencia</h1><p className="subheading">Consulta general y reporte mensual individual con todas las entradas, salidas y reingresos registrados.</p></div>

    <div className="card stack no-print" style={{borderTop:"5px solid #90B4E1"}}>
      <div><h2 style={{margin:"0 0 4px"}}>Reporte mensual individual</h2><div className="muted">Seleccioná un mes y un agente para obtener su historial diario completo de marcaciones.</div></div>
      <div className="form-row"><div><label className="label">Mes</label><input className="input" type="month" value={monthlyMonth} onChange={e=>setMonthlyMonth(e.target.value)}/></div><div><label className="label">Agente</label><select className="select" value={monthlyEmployeeId} onChange={e=>setMonthlyEmployeeId(e.target.value)}><option value="">Seleccionar agente…</option>{monthlyOptions.map(r=><option key={r.id} value={r.id}>{r.last_name}, {r.first_name} · DNI {r.dni}{r.office_name?` · ${r.office_name}`:""}</option>)}</select></div></div>
      <div className="row"><button className="btn btn-primary" type="button" onClick={generateMonthly}>Generar reporte mensual</button><span className="muted">{monthTitle(monthlyMonth)}{monthlyMonth===currentMonthValue()?" · hasta la fecha":""}</span></div>
    </div>

    <div className="card stack no-print">
      <div><h2 style={{margin:"0 0 4px"}}>Reporte general</h2><div className="muted">Podés consultar cualquier rango de fechas, oficina o agente.</div></div>
      <div className="form-row"><div><label className="label">Desde</label><input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><label className="label">Hasta</label><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></div>
      <div className="form-row"><div><label className="label">Oficina / Dirección</label>{offices.length?<select className="select" value={officeId} onChange={e=>setOfficeId(e.target.value)}><option value="">Todas las oficinas habilitadas</option>{offices.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:<input className="input" value={scopeName||"Oficina asignada"} readOnly/>}</div><div><label className="label">Buscar agente</label><input className="input" placeholder="Apellido, nombre o DNI" value={q} onChange={e=>setQ(e.target.value)}/></div></div>
      <div className="row"><button className="btn btn-secondary" type="button" onClick={currentMonth}>Mes actual</button><button className="btn btn-secondary" type="button" onClick={currentYear}>Año actual</button><button className="btn btn-primary" type="button" onClick={()=>{load();if(employeeId)loadDetail(employeeId)}}>{loading?"Actualizando…":"Generar reporte"}</button><div className="spacer"/><button className="btn btn-secondary" type="button" onClick={exportExcel}>Exportar Excel</button><button className="btn btn-secondary" type="button" onClick={()=>window.print()}>Imprimir / guardar PDF</button></div>
      {msg&&<div className="notice bad">{msg}</div>}
    </div>
    <div className="report-print-title"><strong>Ministerio de Educación · Gobierno de Corrientes</strong><div>Reporte de asistencia · {fmtDate(from)} al {fmtDate(to)}</div></div>
    <div className="grid grid-4"><Kpi label="Personal" value={totals.people}/><Kpi label="Faltas justificadas" value={totals.just}/><Kpi label="Faltas injustificadas" value={totals.unjust}/><Kpi label="Minutos a compensar" value={totals.pending}/></div>
    <div className="card table-wrap"><div className="row" style={{marginBottom:10}}><div><h2 style={{margin:0}}>Reporte general</h2><div className="muted">Los contadores respetan la fecha oficial de inicio del control definida para cada oficina.</div></div><div className="spacer"/><span className="badge info">{totals.late} tardanzas</span></div>
      <table><thead><tr><th>Oficina</th><th>Agente</th><th>DNI</th><th>Días previstos</th><th>Faltas</th><th>Justificadas</th><th>Sin justificar</th><th>Tardanzas</th><th>Min. atraso</th><th>Compensados</th><th>A compensar</th><th className="no-print">Detalle</th></tr></thead><tbody>{filtered.length?filtered.map(r=><tr key={r.id}><td>{r.office_name}</td><td><strong>{r.last_name}, {r.first_name}</strong><div className="muted" style={{fontSize:12}}>{r.employment}</div></td><td>{r.dni}</td><td>{r.scheduled_days}</td><td><strong>{r.total_absences}</strong></td><td>{r.justified}</td><td>{r.unjustified>0?<span className="badge danger">{r.unjustified}</span>:0}</td><td>{r.late_entries}</td><td>{r.late_minutes}</td><td>{r.compensated_minutes}</td><td><strong>{r.late_pending_minutes}</strong></td><td className="no-print"><button className="btn btn-secondary" type="button" onClick={()=>loadDetail(String(r.id))}>Ver agente</button></td></tr>):<tr><td colSpan={12} className="muted">No hay datos para los filtros seleccionados.</td></tr>}</tbody></table>
    </div>
    {detail&&<div id="reporte-mensual-individual" className="card stack report-detail"><div className="row"><div><h2 style={{margin:0}}>Reporte individual · {detail.employee.last_name}, {detail.employee.first_name}</h2><div className="muted">DNI {detail.employee.dni} · Período {fmtDate(from)} al {fmtDate(to)}</div></div><div className="spacer"/><div className="row no-print"><button className="btn btn-secondary" type="button" onClick={exportIndividual}>Exportar este agente a Excel</button><button className="btn btn-secondary" type="button" onClick={printIndividual}>Imprimir / PDF individual</button></div></div>
      <div className="grid grid-4"><Kpi label="Presentes" value={detail.summary.present||0}/><Kpi label="Faltas justificadas" value={detail.summary.justified}/><Kpi label="Faltas injustificadas" value={detail.summary.absent}/><Kpi label="Tardanzas" value={detail.summary.lateEntries}/></div>
      <div className="row"><span className="badge info">Atraso acumulado: {detail.summary.lateMinutes} min</span><span className="badge good">Compensados: {detail.summary.compensatedMinutes} min</span><span className="badge info">A compensar: {detailPending} min</span></div>
      <div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Día</th><th>Horario previsto</th><th>Entrada</th><th>Salidas intermedias</th><th>Reingresos</th><th>Salida final</th><th>Estado</th><th>Atraso</th><th>Compensado</th><th>A compensar</th><th>Justificación</th></tr></thead><tbody>{(detail.attendance||[]).map((a:any)=>{const p=movementParts(a);return <tr key={a.work_date}><td>{fmtDate(a.work_date)}</td><td>{fmtDay(a.work_date)}</td><td>{a.scheduled_start||"—"}–{a.scheduled_end||"—"}</td><td><strong>{p.entry}</strong></td><td>{p.intermediate}</td><td>{p.reentries}</td><td><strong>{p.finalExit}</strong></td><td>{statusLabel(a.status)}</td><td>{a.late_minutes||0} min</td><td>{a.compensation_minutes||0} min</td><td>{Math.max(0,Number(a.late_minutes||0)-Number(a.compensation_minutes||0))} min</td><td>{a.type_name||a.leave_type||"—"}{a.article?` · ${a.article}`:""}</td></tr>})}</tbody></table></div>
    </div>}
  </div>
}
