"use client";
import {useEffect,useMemo,useState} from "react";

type Row={id:string;last_name:string;first_name:string;dni:string;employment:string;office_name:string;scheduled_days:number;total_absences:number;justified:number;unjustified:number;late_entries:number;effective_late:number;late_minutes:number;compensated_minutes:number;late_pending_minutes:number;pending_minutes:number};
function localDate(){const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`}
function yearStart(){return `${new Date().getFullYear()}-01-01`}
function fmtDate(v:string){return v?`${v.slice(8,10)}/${v.slice(5,7)}/${v.slice(0,4)}`:"—"}
function esc(v:any){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function Kpi({label,value}:{label:string;value:any}){return <div className="kpi info"><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div></div>}

export default function ReportesPage(){
  const [from,setFrom]=useState(yearStart()),[to,setTo]=useState(localDate()),[officeId,setOfficeId]=useState(""),[rows,setRows]=useState<Row[]>([]),[offices,setOffices]=useState<any[]>([]),[scopeName,setScopeName]=useState(""),[q,setQ]=useState(""),[employeeId,setEmployeeId]=useState(""),[detail,setDetail]=useState<any>(null),[loading,setLoading]=useState(false),[msg,setMsg]=useState("");
  async function load(){setLoading(true);setMsg("");const qs=new URLSearchParams({from,to});if(officeId)qs.set("officeId",officeId);const r=await fetch(`/api/admin/employee-summary?${qs.toString()}`,{cache:"no-store"});const b=await r.json().catch(()=>({}));if(r.ok){setRows(b.rows||[]);setOffices(b.offices||[]);setScopeName(b.officeName||"");if(employeeId&&!b.rows?.some((x:any)=>String(x.id)===String(employeeId))){setEmployeeId("");setDetail(null)}}else setMsg(b.error||"No se pudo generar el reporte");setLoading(false)}
  useEffect(()=>{load()},[]);
  async function loadDetail(id:string){setEmployeeId(id);if(!id){setDetail(null);return}const r=await fetch(`/api/admin/employee-file?employeeId=${encodeURIComponent(id)}&from=${from}&to=${to}`,{cache:"no-store"});const b=await r.json().catch(()=>({}));if(r.ok)setDetail(b);else setMsg(b.error||"No se pudo cargar el detalle del agente")}
  const filtered=useMemo(()=>rows.filter(r=>`${r.last_name} ${r.first_name} ${r.dni} ${r.office_name}`.toLowerCase().includes(q.trim().toLowerCase())),[rows,q]);
  const totals=useMemo(()=>filtered.reduce((a,r)=>({people:a.people+1,abs:a.abs+Number(r.total_absences||0),just:a.just+Number(r.justified||0),unjust:a.unjust+Number(r.unjustified||0),late:a.late+Number(r.late_entries||0),pending:a.pending+Number(r.late_pending_minutes||0)}),{people:0,abs:0,just:0,unjust:0,late:0,pending:0}),[filtered]);
  function currentMonth(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0");setFrom(`${y}-${m}-01`);setTo(localDate())}
  function currentYear(){setFrom(yearStart());setTo(localDate())}
  function exportExcel(){
    const title=`Reporte de asistencia ${fmtDate(from)} al ${fmtDate(to)}`;
    const body=filtered.map(r=>`<tr><td>${esc(r.office_name)}</td><td>${esc(`${r.last_name}, ${r.first_name}`)}</td><td>${esc(r.dni)}</td><td>${r.scheduled_days}</td><td>${r.total_absences}</td><td>${r.justified}</td><td>${r.unjustified}</td><td>${r.late_entries}</td><td>${r.late_minutes}</td><td>${r.compensated_minutes}</td><td>${r.late_pending_minutes}</td></tr>`).join("");
    const html=`<html><head><meta charset="utf-8"></head><body><h2>${esc(title)}</h2><table border="1"><thead><tr><th>Oficina</th><th>Agente</th><th>DNI</th><th>Días previstos</th><th>Faltas totales</th><th>Justificadas</th><th>Injustificadas</th><th>Tardanzas</th><th>Minutos atraso</th><th>Minutos compensados</th><th>Minutos pendientes</th></tr></thead><tbody>${body}</tbody></table></body></html>`;
    const blob=new Blob(["\ufeff",html],{type:"application/vnd.ms-excel;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`reporte_asistencia_${from}_${to}.xls`;a.click();URL.revokeObjectURL(a.href);
  }
  return <div className="stack report-page">
    <div><h1 className="heading">Reportes de asistencia</h1><p className="subheading">Faltas justificadas e injustificadas, tardanzas y minutos de compensación por oficina o agente.</p></div>
    <div className="card stack no-print">
      <div className="form-row"><div><label className="label">Desde</label><input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><label className="label">Hasta</label><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></div>
      <div className="form-row"><div><label className="label">Oficina / Dirección</label>{offices.length?<select className="select" value={officeId} onChange={e=>setOfficeId(e.target.value)}><option value="">Todas las oficinas habilitadas</option>{offices.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:<input className="input" value={scopeName||"Oficina asignada"} readOnly/>}</div><div><label className="label">Buscar agente</label><input className="input" placeholder="Apellido, nombre o DNI" value={q} onChange={e=>setQ(e.target.value)}/></div></div>
      <div className="row"><button className="btn btn-secondary" type="button" onClick={currentMonth}>Mes actual</button><button className="btn btn-secondary" type="button" onClick={currentYear}>Año actual</button><button className="btn btn-primary" type="button" onClick={()=>{load();if(employeeId)loadDetail(employeeId)}}>{loading?"Actualizando…":"Generar reporte"}</button><div className="spacer"/><button className="btn btn-secondary" type="button" onClick={exportExcel}>Exportar Excel</button><button className="btn btn-secondary" type="button" onClick={()=>window.print()}>Imprimir / guardar PDF</button></div>
      {msg&&<div className="notice bad">{msg}</div>}
    </div>
    <div className="report-print-title"><strong>Ministerio de Educación · Gobierno de Corrientes</strong><div>Reporte de asistencia · {fmtDate(from)} al {fmtDate(to)}</div></div>
    <div className="grid grid-4"><Kpi label="Personal" value={totals.people}/><Kpi label="Faltas justificadas" value={totals.just}/><Kpi label="Faltas injustificadas" value={totals.unjust}/><Kpi label="Minutos a compensar" value={totals.pending}/></div>
    <div className="card table-wrap"><div className="row" style={{marginBottom:10}}><div><h2 style={{margin:0}}>Reporte general</h2><div className="muted">Los contadores respetan la fecha oficial de inicio del control definida para cada oficina.</div></div><div className="spacer"/><span className="badge info">{totals.late} tardanzas</span></div>
      <table><thead><tr><th>Oficina</th><th>Agente</th><th>DNI</th><th>Días previstos</th><th>Faltas</th><th>Justificadas</th><th>Sin justificar</th><th>Tardanzas</th><th>Min. atraso</th><th>Compensados</th><th>A compensar</th><th className="no-print">Detalle</th></tr></thead><tbody>{filtered.length?filtered.map(r=><tr key={r.id}><td>{r.office_name}</td><td><strong>{r.last_name}, {r.first_name}</strong><div className="muted" style={{fontSize:12}}>{r.employment}</div></td><td>{r.dni}</td><td>{r.scheduled_days}</td><td><strong>{r.total_absences}</strong></td><td>{r.justified}</td><td>{r.unjustified>0?<span className="badge danger">{r.unjustified}</span>:0}</td><td>{r.late_entries}</td><td>{r.late_minutes}</td><td>{r.compensated_minutes}</td><td><strong>{r.late_pending_minutes}</strong></td><td className="no-print"><button className="btn btn-secondary" type="button" onClick={()=>loadDetail(String(r.id))}>Ver agente</button></td></tr>):<tr><td colSpan={12} className="muted">No hay datos para los filtros seleccionados.</td></tr>}</tbody></table>
    </div>
    {detail&&<div className="card stack report-detail"><div><h2 style={{margin:0}}>{detail.employee.last_name}, {detail.employee.first_name}</h2><div className="muted">DNI {detail.employee.dni} · Período {fmtDate(from)} al {fmtDate(to)}</div></div>
      <div className="grid grid-4"><Kpi label="Faltas justificadas" value={detail.summary.justified}/><Kpi label="Faltas injustificadas" value={detail.summary.absent}/><Kpi label="Tardanzas" value={detail.summary.lateEntries}/><Kpi label="Minutos a compensar" value={(detail.attendance||[]).reduce((s:number,a:any)=>s+Math.max(0,Number(a.late_minutes||0)-Number(a.compensation_minutes||0)),0)}/></div>
      <div className="row"><span className="badge info">Atraso acumulado: {detail.summary.lateMinutes} min</span><span className="badge good">Compensados: {detail.summary.compensatedMinutes} min</span></div>
      <div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Estado</th><th>Horario</th><th>Entrada</th><th>Salida</th><th>Atraso</th><th>Compensado</th><th>A compensar</th><th>Justificación</th></tr></thead><tbody>{(detail.attendance||[]).map((a:any)=><tr key={a.work_date}><td>{fmtDate(a.work_date)}</td><td>{a.status==="PRESENT"?"Presente":a.status==="JUSTIFIED"?"Justificada":a.status==="ABSENT"?"Sin justificar":"Pendiente"}</td><td>{a.scheduled_start||"—"}–{a.scheduled_end||"—"}</td><td>{a.entry_local||"—"}</td><td>{a.exit_local||"—"}</td><td>{a.late_minutes||0} min</td><td>{a.compensation_minutes||0} min</td><td>{Math.max(0,Number(a.late_minutes||0)-Number(a.compensation_minutes||0))} min</td><td>{a.type_name||a.leave_type||"—"}{a.article?` · ${a.article}`:""}</td></tr>)}</tbody></table></div>
    </div>}
  </div>
}
