"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type LeaveType={id:number;code:string;name:string;article?:string;category:string;day_basis:string;annual_limit?:number;monthly_limit?:number;event_limit?:number;extension_limit?:number;pay_rule?:string;notes?:string;active:boolean};
export default function NovedadesPage(){
 const [employees,setEmployees]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[types,setTypes]=useState<LeaveType[]>([]),[msg,setMsg]=useState("");
 const [mode,setMode]=useState("LICENSE"); const [form,setForm]=useState({employeeId:"",leaveTypeId:"",dateFrom:"",dateTo:"",observation:""});
 const [showCatalog,setShowCatalog]=useState(false); const [catalog,setCatalog]=useState({code:"",name:"",article:"",category:"ADMINISTRATIVE",dayBasis:"CALENDAR",annualLimit:"",monthlyLimit:"",eventLimit:"",extensionLimit:"",payRule:"",notes:""});
 async function load(){const [e,l,t]=await Promise.all([fetch("/api/admin/employees"),fetch("/api/admin/leaves"),fetch("/api/admin/leave-types")]);if(e.ok)setEmployees(await e.json());if(l.ok)setRows(await l.json());if(t.ok)setTypes(await t.json());}
 useEffect(()=>{load();},[]); const selected=useMemo(()=>types.find(t=>String(t.id)===form.leaveTypeId),[types,form.leaveTypeId]);
 async function submit(ev:FormEvent){ev.preventDefault();setMsg("");const r=await fetch("/api/admin/leaves",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,mode})});const b=await r.json().catch(()=>({}));if(!r.ok){setMsg(b.error||"No se pudo guardar");return;}setMsg(`Registro guardado. ${b.computedDays??""} días computados.${b.warning?" ADVERTENCIA: "+b.warning:""}`);setForm({...form,dateFrom:"",dateTo:"",observation:""});await load();}
 async function createType(ev:FormEvent){ev.preventDefault();const r=await fetch("/api/admin/leave-types",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(catalog)});const b=await r.json().catch(()=>({}));if(!r.ok){setMsg(b.error||"No se pudo crear el tipo");return;}setShowCatalog(false);setCatalog({code:"",name:"",article:"",category:"ADMINISTRATIVE",dayBasis:"CALENDAR",annualLimit:"",monthlyLimit:"",eventLimit:"",extensionLimit:"",payRule:"",notes:""});setMsg("Tipo de licencia agregado al catálogo.");await load();}
 async function remove(id:number){if(!confirm("¿Desactivar este registro?"))return;const r=await fetch(`/api/admin/leaves?id=${id}`,{method:"DELETE"});if(r.ok)await load();}
 return <div className="stack"><div><h1 className="heading">Licencias y vacaciones</h1><p className="subheading">Catálogo normativo administrable y carga manual por agente. Las vacaciones se registran siempre manualmente.</p></div>
  <div className="card stack"><div className="form-row"><button type="button" className={`btn ${mode==="LICENSE"?"btn-primary":"btn-secondary"}`} onClick={()=>setMode("LICENSE")}>Registrar licencia</button><button type="button" className={`btn ${mode==="VACATION"?"btn-primary":"btn-secondary"}`} onClick={()=>setMode("VACATION")}>Registrar vacaciones</button><button type="button" className="btn btn-secondary" onClick={()=>setShowCatalog(true)}>+ Agregar tipo de licencia</button></div></div>
  <form className="card stack" onSubmit={submit}><div className="form-row"><div><label className="label">Agente</label><select className="select" required value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}><option value="">Seleccionar…</option>{employees.map(e=><option key={e.id} value={e.id}>{e.last_name}, {e.first_name}</option>)}</select></div>{mode==="LICENSE"&&<div><label className="label">Tipo de licencia</label><select className="select" required value={form.leaveTypeId} onChange={e=>setForm({...form,leaveTypeId:e.target.value})}><option value="">Seleccionar…</option><optgroup label="Licencias médicas">{types.filter(t=>t.active&&t.category==="MEDICAL").map(t=><option key={t.id} value={t.id}>{t.article?`${t.article} — `:""}{t.name}</option>)}</optgroup><optgroup label="Licencias administrativas">{types.filter(t=>t.active&&t.category==="ADMINISTRATIVE").map(t=><option key={t.id} value={t.id}>{t.article?`${t.article} — `:""}{t.name}</option>)}</optgroup></select></div>}</div>
   {mode==="LICENSE"&&selected&&<div className="notice info"><strong>{selected.article} — {selected.name}</strong><br/>{selected.pay_rule||""}{selected.annual_limit?` · Máx. anual: ${selected.annual_limit} días`:""}{selected.monthly_limit?` · Máx. mensual: ${selected.monthly_limit} días`:""}{selected.event_limit?` · Máx. por evento: ${selected.event_limit} días`:""}<br/><span>{selected.notes}</span></div>}
   {mode==="VACATION"&&<div className="notice info">Las vacaciones se asignan manualmente por agente. El sistema calcula los días del período, pero no asigna fechas automáticamente.</div>}
   <div className="form-row"><div><label className="label">Desde</label><input className="input" type="date" required value={form.dateFrom} onChange={e=>setForm({...form,dateFrom:e.target.value})}/></div><div><label className="label">Hasta</label><input className="input" type="date" required value={form.dateTo} onChange={e=>setForm({...form,dateTo:e.target.value})}/></div></div><div><label className="label">Observación</label><textarea className="textarea" value={form.observation} onChange={e=>setForm({...form,observation:e.target.value})}/></div>{msg&&<div className={`notice ${msg.includes("ADVERTENCIA")||msg.includes("No se pudo")?"bad":"good"}`}>{msg}</div>}<button className="btn btn-primary">Guardar</button></form>
  <div className="card table-wrap"><table><thead><tr><th>Agente</th><th>Tipo</th><th>Desde</th><th>Hasta</th><th>Días</th><th>Observación</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.last_name}, {r.first_name}</td><td>{r.type_name?`${r.article?`${r.article} — `:""}${r.type_name}`:r.leave_type==="VACATION"?"Vacaciones":r.leave_type}</td><td>{r.date_from}</td><td>{r.date_to}</td><td>{r.computed_days??"—"}{r.warning_text&&<div className="badge warn">Advertencia</div>}</td><td>{r.observation||"—"}</td><td><button className="btn btn-secondary" onClick={()=>remove(r.id)}>Desactivar</button></td></tr>)}</tbody></table></div>
  {showCatalog&&<div className="modal-backdrop"><form className="modal-card stack" onSubmit={createType}><div><h2 className="heading" style={{fontSize:"1.25rem"}}>Agregar tipo de licencia</h2><p className="subheading">Quedará disponible en el selector para futuras cargas.</p></div><div className="form-row"><div><label className="label">Código</label><input className="input" required value={catalog.code} onChange={e=>setCatalog({...catalog,code:e.target.value})}/></div><div><label className="label">Artículo / norma</label><input className="input" value={catalog.article} onChange={e=>setCatalog({...catalog,article:e.target.value})}/></div></div><div><label className="label">Nombre</label><input className="input" required value={catalog.name} onChange={e=>setCatalog({...catalog,name:e.target.value})}/></div><div className="form-row"><div><label className="label">Categoría</label><select className="select" value={catalog.category} onChange={e=>setCatalog({...catalog,category:e.target.value})}><option value="MEDICAL">Médica</option><option value="ADMINISTRATIVE">Administrativa</option></select></div><div><label className="label">Cómputo</label><select className="select" value={catalog.dayBasis} onChange={e=>setCatalog({...catalog,dayBasis:e.target.value})}><option value="CALENDAR">Días corridos</option><option value="BUSINESS">Días hábiles (lun-vie)</option><option value="MANUAL">Período manual</option></select></div></div><div className="form-row"><div><label className="label">Máx. anual</label><input className="input" type="number" min="0" value={catalog.annualLimit} onChange={e=>setCatalog({...catalog,annualLimit:e.target.value})}/></div><div><label className="label">Máx. mensual</label><input className="input" type="number" min="0" value={catalog.monthlyLimit} onChange={e=>setCatalog({...catalog,monthlyLimit:e.target.value})}/></div></div><div className="form-row"><div><label className="label">Máx. por evento</label><input className="input" type="number" min="0" value={catalog.eventLimit} onChange={e=>setCatalog({...catalog,eventLimit:e.target.value})}/></div><div><label className="label">Prórroga</label><input className="input" type="number" min="0" value={catalog.extensionLimit} onChange={e=>setCatalog({...catalog,extensionLimit:e.target.value})}/></div></div><div><label className="label">Régimen de haberes</label><input className="input" value={catalog.payRule} onChange={e=>setCatalog({...catalog,payRule:e.target.value})}/></div><div><label className="label">Observaciones / condiciones</label><textarea className="textarea" value={catalog.notes} onChange={e=>setCatalog({...catalog,notes:e.target.value})}/></div><div className="form-row"><button className="btn btn-primary">Guardar tipo</button><button type="button" className="btn btn-secondary" onClick={()=>setShowCatalog(false)}>Cancelar</button></div></form></div>}
 </div>;
}
