"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type LeaveType={id:number;code:string;name:string;article?:string;category:string;day_basis:string;annual_limit?:number;monthly_limit?:number;event_limit?:number;extension_limit?:number;pay_rule?:string;notes?:string;active:boolean};
export default function NovedadesPage(){
 const [employees,setEmployees]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[types,setTypes]=useState<LeaveType[]>([]),[msg,setMsg]=useState(""),[role,setRole]=useState("LICENSE_OPERATOR"),[meEmail,setMeEmail]=useState("");
 const [mode,setMode]=useState("LICENSE"),[balance,setBalance]=useState<any>(null),[vacStatus,setVacStatus]=useState<any>(null);
 const [form,setForm]=useState({employeeId:"",leaveTypeId:"",dateFrom:"",dateTo:"",observation:""});
 const [vac,setVac]=useState({year:String(new Date().getFullYear()),seniorityYears:"",serviceMonths:"12",extraFractionOver15:false,notes:""});
 const [showCatalog,setShowCatalog]=useState(false); const [historyFilter,setHistoryFilter]=useState("ALL"),[historyEmployee,setHistoryEmployee]=useState(""); const [catalog,setCatalog]=useState({code:"",name:"",article:"",category:"ADMINISTRATIVE",dayBasis:"CALENDAR",annualLimit:"",monthlyLimit:"",eventLimit:"",extensionLimit:"",payRule:"",notes:""});
 async function load(){const [e,l,t,m]=await Promise.all([fetch("/api/admin/employees"),fetch("/api/admin/leaves"),fetch("/api/admin/leave-types"),fetch("/api/admin/me")]);if(e.ok)setEmployees(await e.json());if(l.ok)setRows(await l.json());if(t.ok)setTypes(await t.json());if(m.ok){const mb=await m.json();setRole(mb.role);setMeEmail(mb.email||"");}}
 useEffect(()=>{load();},[]); const selected=useMemo(()=>types.find(t=>String(t.id)===form.leaveTypeId),[types,form.leaveTypeId]);
 useEffect(()=>{(async()=>{setBalance(null);if(mode!=="LICENSE"||!form.employeeId||!form.leaveTypeId)return;const date=form.dateFrom||new Date().toISOString().slice(0,10);const r=await fetch(`/api/admin/leave-balance?employeeId=${encodeURIComponent(form.employeeId)}&leaveTypeId=${form.leaveTypeId}&date=${date}`);if(r.ok)setBalance(await r.json());})()},[mode,form.employeeId,form.leaveTypeId,form.dateFrom,rows.length]);
 useEffect(()=>{(async()=>{setVacStatus(null);if(mode!=="VACATION"||!form.employeeId)return;const year=Number(vac.year)||new Date().getFullYear();const r=await fetch(`/api/admin/vacation-status?employeeId=${encodeURIComponent(form.employeeId)}&year=${year}`);if(r.ok){const b=await r.json();setVacStatus(b);if(b.profile)setVac({year:String(year),seniorityYears:String(b.profile.seniority_years),serviceMonths:String(b.profile.service_months),extraFractionOver15:Boolean(b.profile.extra_fraction_over_15),notes:b.profile.notes||""});else if(b.seniorityReference!==null&&b.seniorityReference!==undefined)setVac(v=>({...v,year:String(year),seniorityYears:String(b.seniorityReference)}));}})()},[mode,form.employeeId,vac.year,rows.length]);
 async function submit(ev:FormEvent){ev.preventDefault();setMsg("");if(mode==="VACATION"&&form.employeeId&&vac.seniorityYears!==""){const vr=await fetch("/api/admin/vacation-status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({employeeId:form.employeeId,year:Number(vac.year),seniorityYears:Number(vac.seniorityYears),serviceMonths:Number(vac.serviceMonths),extraFractionOver15:vac.extraFractionOver15,notes:vac.notes})});const vb=await vr.json().catch(()=>({}));if(!vr.ok){setMsg(vb.error||"No se pudo guardar el cálculo de vacaciones");return;}}
  const r=await fetch("/api/admin/leaves",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,mode})});const b=await r.json().catch(()=>({}));if(!r.ok){setMsg(b.error||"No se pudo guardar");return;}setMsg(`Registro guardado. ${b.computedDays??""} días computados.${b.warning?" ADVERTENCIA: "+b.warning:""}`);setForm({...form,dateFrom:"",dateTo:"",observation:""});await load();}
 async function createType(ev:FormEvent){ev.preventDefault();const r=await fetch("/api/admin/leave-types",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(catalog)});const b=await r.json().catch(()=>({}));if(!r.ok){setMsg(b.error||"No se pudo crear el tipo");return;}setShowCatalog(false);setMsg("Tipo agregado al catálogo.");await load();}
 async function remove(id:number){if(!confirm("¿Desactivar este registro?"))return;const r=await fetch(`/api/admin/leaves?id=${id}`,{method:"DELETE"});const b=await r.json().catch(()=>({}));if(!r.ok){setMsg(b.error||"No se pudo desactivar");return;}await load();}
 const isAdmin=role==="ADMIN";
 const visibleRows=rows.filter((r:any)=>{if(historyEmployee&&String(r.employee_id||"")!==historyEmployee)return false;if(historyFilter==="MEDICAL")return r.category==="MEDICAL"||(!r.category&&r.leave_type==="MEDICAL");if(historyFilter==="ADMINISTRATIVE")return r.category==="ADMINISTRATIVE"||(!r.category&&r.leave_type==="ADMINISTRATIVE");if(historyFilter==="VACATION")return r.leave_type==="VACATION";return true;});
 return <div className="stack"><div><h1 className="heading">Licencias y vacaciones</h1><p className="subheading">Carga por agente con control automático de límites, saldos y excesos.</p></div>
  <div className="card"><div className="form-row"><button type="button" className={`btn ${mode==="LICENSE"?"btn-primary":"btn-secondary"}`} onClick={()=>setMode("LICENSE")}>Registrar licencia</button><button type="button" className={`btn ${mode==="VACATION"?"btn-primary":"btn-secondary"}`} onClick={()=>setMode("VACATION")}>Registrar vacaciones</button>{isAdmin&&<button type="button" className="btn btn-secondary" onClick={()=>setShowCatalog(true)}>+ Agregar tipo de licencia</button>}</div></div>
  <form className="card stack" onSubmit={submit}><div className="form-row"><div><label className="label">Agente</label><select className="select" required value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}><option value="">Seleccionar…</option>{employees.filter(e=>e.active).map(e=><option key={e.id} value={e.id}>{e.last_name}, {e.first_name}</option>)}</select></div>{mode==="LICENSE"&&<div><label className="label">Tipo de licencia</label><select className="select" required value={form.leaveTypeId} onChange={e=>setForm({...form,leaveTypeId:e.target.value})}><option value="">Seleccionar…</option><optgroup label="Licencias médicas">{types.filter(t=>t.active&&t.category==="MEDICAL").map(t=><option key={t.id} value={t.id}>{t.article?`${t.article} — `:""}{t.name}</option>)}</optgroup><optgroup label="Licencias / justificaciones administrativas">{types.filter(t=>t.active&&t.category==="ADMINISTRATIVE").map(t=><option key={t.id} value={t.id}>{t.article?`${t.article} — `:""}{t.name}</option>)}</optgroup></select></div>}</div>
   {mode==="LICENSE"&&selected&&<div className="notice info"><strong>{selected.article} — {selected.name}</strong><br/>{selected.pay_rule||""}{selected.annual_limit?` · Máx. anual: ${selected.annual_limit}`:""}{selected.monthly_limit?` · Máx. mensual: ${selected.monthly_limit}`:""}{selected.event_limit?` · Máx. por evento: ${selected.event_limit}`:""}<br/>{selected.notes}</div>}
   {mode==="LICENSE"&&balance&&<div className={`notice ${(balance.annualExcess||balance.monthlyExcess||balance.detail?.excess)>0?"bad":"good"}`}><strong>Estado del agente para esta licencia</strong><br/>Usado en el año: <strong>{balance.annualUsed}</strong>{balance.annualLimit!==null?` / ${balance.annualLimit}`:""}{balance.annualRemaining!==null?` · Disponible: ${balance.annualRemaining}`:""}{balance.annualExcess?` · Exceso: ${balance.annualExcess}`:""}<br/>{balance.monthlyLimit!==null&&<>Usado en el mes: <strong>{balance.monthlyUsed} / {balance.monthlyLimit}</strong> · Disponible mensual: {balance.monthlyRemaining}{balance.monthlyExcess?` · Exceso mensual: ${balance.monthlyExcess}`:""}<br/></>}{balance.detail?.remainingWithPay!==undefined&&<>Con goce disponible: {balance.detail.remainingWithPay} · Exceso/sin goce: {balance.detail.excessWithoutPay||0}<br/></>}{balance.detail?.remainingWithoutPay!==undefined&&<>Tramo sin goce disponible: {balance.detail.remainingWithoutPay} · Exceso total: {balance.detail.excess||0}<br/></>}{balance.detail?.remainingExtension!==undefined&&<>Prórroga disponible: {balance.detail.remainingExtension} · Exceso: {balance.detail.excess||0}</>}</div>}
   {mode==="VACATION"&&<><div className="notice info"><strong>Licencia Ordinaria — Arts. 4 y 5.</strong> La fecha de vacaciones se registra manualmente. El sistema calcula un derecho de referencia según antigüedad: 20 / 25 / 30 / 35 días corridos. Para interinos con menos de 6 meses de servicios reales, calcula 1/12 por mes o fracción mayor de 15 días. Los períodos Art. 8 b, Art. 8 c y licencias/disponibilidad sin goce no generan derecho y deben descontarse al definir los meses computables.</div><div className="form-row"><div><label className="label">Año del beneficio</label><input className="input" type="number" min="2020" max="2100" value={vac.year} onChange={e=>setVac({...vac,year:e.target.value})}/></div><div><label className="label">Antigüedad computable (años)</label><input className="input" type="number" min="0" max="60" required value={vac.seniorityYears} onChange={e=>setVac({...vac,seniorityYears:e.target.value})}/><div className="muted">Se completa automáticamente si el agente tiene fecha de antigüedad registrada; puede ajustarse para este beneficio.</div></div><div><label className="label">Meses de servicios reales computables</label><input className="input" type="number" min="0" max="12" required value={vac.serviceMonths} onChange={e=>setVac({...vac,serviceMonths:e.target.value})}/></div></div><label className="form-check"><input type="checkbox" checked={vac.extraFractionOver15} onChange={e=>setVac({...vac,extraFractionOver15:e.target.checked})}/><span>Existe una fracción adicional mayor de 15 días (suma 1/12 cuando corresponde proporcional)</span></label>{vacStatus&&<div className={`notice ${vacStatus.excess>0?"bad":"good"}`}><strong>Vacaciones {vac.year}</strong><br/>Derecho calculado: {vacStatus.entitlementDays??"Pendiente de guardar parámetros"} días · Usados: {vacStatus.usedDays} · Saldo: {vacStatus.balance??"—"}{vacStatus.excess>0?` · Exceso: ${vacStatus.excess}`:""}</div>}</>}
   <div className="form-row"><div><label className="label">Desde</label><input className="input" type="date" required value={form.dateFrom} onChange={e=>setForm({...form,dateFrom:e.target.value})}/></div><div><label className="label">Hasta</label><input className="input" type="date" required value={form.dateTo} onChange={e=>setForm({...form,dateTo:e.target.value})}/></div></div><div><label className="label">Observación</label><textarea className="textarea" value={form.observation} onChange={e=>setForm({...form,observation:e.target.value})}/></div>{msg&&<div className={`notice ${msg.includes("ADVERTENCIA")||msg.includes("No se pudo")?"bad":"good"}`}>{msg}</div>}<button className="btn btn-primary">Guardar</button></form>
  <div className="card stack"><div><h2 style={{margin:0}}>Historial de licencias y vacaciones</h2><p className="subheading">Usá los filtros para ver específicamente licencias médicas, administrativas o vacaciones.</p></div><div className="form-row"><div><label className="label">Tipo de registro</label><select className="select" value={historyFilter} onChange={e=>setHistoryFilter(e.target.value)}><option value="ALL">Todos</option><option value="MEDICAL">Licencias médicas</option><option value="ADMINISTRATIVE">Licencias administrativas</option><option value="VACATION">Vacaciones</option></select></div><div><label className="label">Agente</label><select className="select" value={historyEmployee} onChange={e=>setHistoryEmployee(e.target.value)}><option value="">Todos los agentes</option>{employees.map(e=><option key={e.id} value={e.id}>{e.last_name}, {e.first_name}</option>)}</select></div></div><div className="table-wrap"><table><thead><tr><th>Agente</th><th>Tipo</th><th>Desde</th><th>Hasta</th><th>Días</th><th>Cargado por</th><th></th></tr></thead><tbody>{visibleRows.map(r=><tr key={r.id}><td>{r.last_name}, {r.first_name}</td><td>{r.type_name?`${r.article?`${r.article} — `:""}${r.type_name}`:r.leave_type==="VACATION"?"Vacaciones":r.leave_type}</td><td>{r.date_from}</td><td>{r.date_to}</td><td>{r.computed_days??"—"}{r.warning_text&&<div className="badge warn">Advertencia</div>}</td><td>{r.created_by||"—"}</td><td>{(isAdmin||String(r.created_by||"").toLowerCase()===meEmail.toLowerCase())&&<button className="btn btn-secondary" onClick={()=>remove(r.id)}>Desactivar</button>}</td></tr>)}</tbody></table></div></div>
  {showCatalog&&isAdmin&&<div className="modal-backdrop"><div className="modal-card"><form className="stack" onSubmit={createType}><h2 style={{margin:0}}>Agregar tipo de licencia</h2><div className="form-row"><div><label className="label">Código</label><input className="input" required value={catalog.code} onChange={e=>setCatalog({...catalog,code:e.target.value})}/></div><div><label className="label">Artículo</label><input className="input" value={catalog.article} onChange={e=>setCatalog({...catalog,article:e.target.value})}/></div></div><div><label className="label">Nombre</label><input className="input" required value={catalog.name} onChange={e=>setCatalog({...catalog,name:e.target.value})}/></div><div className="form-row"><div><label className="label">Categoría</label><select className="select" value={catalog.category} onChange={e=>setCatalog({...catalog,category:e.target.value})}><option value="MEDICAL">Médica</option><option value="ADMINISTRATIVE">Administrativa</option></select></div><div><label className="label">Cómputo</label><select className="select" value={catalog.dayBasis} onChange={e=>setCatalog({...catalog,dayBasis:e.target.value})}><option value="CALENDAR">Días corridos</option><option value="BUSINESS">Días hábiles</option><option value="MANUAL">Manual</option></select></div></div><div className="form-row"><div><label className="label">Máx. anual</label><input className="input" type="number" min="0" value={catalog.annualLimit} onChange={e=>setCatalog({...catalog,annualLimit:e.target.value})}/></div><div><label className="label">Máx. mensual</label><input className="input" type="number" min="0" value={catalog.monthlyLimit} onChange={e=>setCatalog({...catalog,monthlyLimit:e.target.value})}/></div></div><div className="form-row"><button className="btn btn-primary">Guardar tipo</button><button type="button" className="btn btn-secondary" onClick={()=>setShowCatalog(false)}>Cancelar</button></div></form></div></div>}
 </div>;
}
