"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Schedule = { weekday:number; start_time:string; end_time:string };
type Employee = { id:string; last_name:string; first_name:string; dni:string; employment:string; seniority_date?:string|null; seniority_notes?:string|null; active:boolean; pin_configured:boolean; force_pin_change?:boolean; pin_changed_at?:string|null; pin_change_source?:string|null; pin_reset_count?:number; temporary_pin_expires_at?:string|null; schedules:Schedule[]; active_devices:number; device_last_seen?:string|null };
type BulkPinRow={id:string;lastName:string;firstName:string;dni:string;pin:string;expiresAt:string};
type EditSchedule={weekday:number;works:boolean;start:string;end:string};
const days=[{n:1,l:"Lunes"},{n:2,l:"Martes"},{n:3,l:"Miércoles"},{n:4,l:"Jueves"},{n:5,l:"Viernes"}];
const dayNames:Record<number,string>={1:"Lun",2:"Mar",3:"Mié",4:"Jue",5:"Vie"};
const blankSchedules=()=>days.map(d=>({weekday:d.n,works:false,start:"08:00",end:"13:00"}));

export default function PersonalPage(){
 const [employees,setEmployees]=useState<Employee[]>([]),[search,setSearch]=useState(""),[msg,setMsg]=useState("");
 const [mode,setMode]=useState<"none"|"new"|"edit"|"pin"|"device"|"bulkpin">("none"); const [selected,setSelected]=useState<Employee|null>(null); const [pin,setPin]=useState(""); const [forcePinChange,setForcePinChange]=useState(true);
 const [bulkPins,setBulkPins]=useState<BulkPinRow[]>([]),[bulkLoading,setBulkLoading]=useState(false),[bulkMsg,setBulkMsg]=useState("");
 const [form,setForm]=useState({lastName:"",firstName:"",dni:"",employment:"",seniorityDate:"",seniorityNotes:"",active:true,schedules:blankSchedules()});
 async function load(){const r=await fetch("/api/admin/employees",{cache:"no-store"});if(r.ok)setEmployees(await r.json());}
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return !q?employees:employees.filter(e=>`${e.last_name} ${e.first_name} ${e.dni}`.toLowerCase().includes(q));},[employees,search]);
 function openNew(){setSelected(null);setMode("new");setMsg("");setPin("");setForm({lastName:"",firstName:"",dni:"",employment:"",seniorityDate:"",seniorityNotes:"",active:true,schedules:blankSchedules()});}
 function openEdit(e:Employee){const schedules=blankSchedules().map(s=>{const x=e.schedules.find(a=>a.weekday===s.weekday);return x?{weekday:s.weekday,works:true,start:String(x.start_time).slice(0,5),end:String(x.end_time).slice(0,5)}:s});setSelected(e);setMode("edit");setMsg("");setForm({lastName:e.last_name,firstName:e.first_name,dni:e.dni,employment:e.employment,seniorityDate:e.seniority_date||"",seniorityNotes:e.seniority_notes||"",active:e.active,schedules});}
 async function saveEmployee(ev:FormEvent){ev.preventDefault();setMsg("");const url=mode==="new"?"/api/admin/employees":`/api/admin/employees/${selected?.id}`;const method=mode==="new"?"POST":"PUT";const body={...form,pin:mode==="new"?pin:undefined};const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const b=await r.json().catch(()=>({}));if(!r.ok){setMsg(b.error||"No se pudo guardar");return;}setMsg("Datos guardados correctamente.");await load();if(mode==="new"){setMode("none");}}
 async function savePin(ev:FormEvent){ev.preventDefault();if(!selected)return;setMsg("");const r=await fetch(`/api/admin/employees/${selected.id}/pin`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pin,forceChange:forcePinChange})});const b=await r.json().catch(()=>({}));if(!r.ok){setMsg(b.error||"No se pudo guardar el PIN");return;}setMsg(forcePinChange?"PIN temporal asignado correctamente. El agente deberá cambiarlo en su próximo ingreso.":"PIN actualizado correctamente.");setPin("");await load();}

 async function generateBulkPins(){
  if(!confirm("Se generará un PIN provisorio para cada agente activo que todavía no tenga PIN. Los PIN vencerán en 7 días y deberán cambiarse en el primer uso. ¿Continuar?"))return;
  setBulkLoading(true);setBulkMsg("");setBulkPins([]);
  const r=await fetch("/api/admin/employees/bulk-pins",{method:"POST"}); const b=await r.json().catch(()=>({})); setBulkLoading(false);
  if(!r.ok){setBulkMsg(b.error||"No se pudieron generar los PIN");return;}
  setBulkPins(Array.isArray(b.generated)?b.generated:[]); setBulkMsg(Number(b.count||0)>0?`Se generaron ${b.count} PIN provisorios. Descargá el listado ahora: por seguridad no volverán a mostrarse.`:(b.message||"No hay agentes pendientes de PIN.")); await load();
 }
 function downloadBulkPins(){
  if(!bulkPins.length)return; const header=["Apellido y nombre","DNI","PIN provisorio","Vence"]; const rows=bulkPins.map(x=>[`${x.lastName}, ${x.firstName}`,x.dni,x.pin,new Date(x.expiresAt).toLocaleDateString("es-AR")]);
  const esc=(v:string)=>`"${String(v).replace(/"/g,'""')}"`; const csv="\ufeff"+[header,...rows].map(r=>r.map(esc).join(";")).join("\r\n");
  const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=`PIN_provisorios_DGE_${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url);
 }
 async function revokeDevice(){if(!selected||!confirm("¿Desvincular el dispositivo autorizado de este agente? Deberá vincular nuevamente su celular en la próxima marcación."))return;const r=await fetch(`/api/admin/employees/${selected.id}/device`,{method:"DELETE"});const b=await r.json().catch(()=>({}));setMsg(r.ok?"Dispositivo desvinculado correctamente.":b.error||"No se pudo desvincular");await load();}
 function setSchedule(i:number,key:"works"|"start"|"end",value:boolean|string){setForm(f=>({...f,schedules:f.schedules.map((s,idx)=>idx===i?{...s,[key]:value}:s)}));}
 return <div className="stack">
  <div className="row"><div><h1 className="heading">Personal</h1><p className="subheading">Alta, edición de datos, horarios, PIN y dispositivo autorizado.</p></div><div className="spacer"/><button className="btn btn-secondary" onClick={()=>{setMode("bulkpin");setBulkPins([]);setBulkMsg("");}}>Generar PIN provisorios</button><button className="btn btn-primary" onClick={openNew}>+ Agregar personal</button></div>
  {mode!=="none"&&<div className="modal-backdrop" role="presentation"><div className="modal-panel" role="dialog" aria-modal="true" aria-label="Gestión de personal">
  {(mode==="new"||mode==="edit")&&<div className="stack"><div className="row"><strong>{mode==="new"?"Agregar personal":`Editar ${selected?.last_name}, ${selected?.first_name}`}</strong><div className="spacer"/><button className="btn btn-secondary" onClick={()=>setMode("none")}>Cerrar</button></div><form className="stack" onSubmit={saveEmployee}><div className="form-row"><div><label className="label">Apellido</label><input className="input" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} required/></div><div><label className="label">Nombre</label><input className="input" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} required/></div></div><div className="form-row"><div><label className="label">DNI</label><input className="input" inputMode="numeric" value={form.dni} onChange={e=>setForm({...form,dni:e.target.value.replace(/\D/g,"")})} required/></div><div><label className="label">Situación de revista</label><input className="input" value={form.employment} onChange={e=>setForm({...form,employment:e.target.value})} required/></div></div><div className="form-row"><div><label className="label">Fecha de antigüedad reconocida</label><input className="input" type="date" value={form.seniorityDate} onChange={e=>setForm({...form,seniorityDate:e.target.value})}/><div className="muted">Se usa para calcular el tramo de Licencia Ordinaria al 31/12 del año del beneficio.</div></div><div><label className="label">Observación de antigüedad</label><input className="input" value={form.seniorityNotes} onChange={e=>setForm({...form,seniorityNotes:e.target.value})} placeholder="Opcional"/></div></div>{mode==="new"&&<div><label className="label">PIN inicial (opcional, 4 a 8 dígitos)</label><input className="input" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} minLength={4} maxLength={8}/></div>}<div><div className="label">Horario semanal</div><div className="stack">{form.schedules.map((s,i)=><div key={s.weekday} className="form-row" style={{alignItems:"end"}}><label className="row" style={{minHeight:44}}><input type="checkbox" checked={s.works} onChange={e=>setSchedule(i,"works",e.target.checked)}/><strong>{days[i].l}</strong></label><div><label className="label">Entrada</label><input className="input" type="time" disabled={!s.works} value={s.start} onChange={e=>setSchedule(i,"start",e.target.value)}/></div><div><label className="label">Salida</label><input className="input" type="time" disabled={!s.works} value={s.end} onChange={e=>setSchedule(i,"end",e.target.value)}/></div></div>)}</div></div>{mode==="edit"&&<label className="row"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span>Agente activo</span></label>}{msg&&<div className={`notice ${msg.includes("correctamente")?"good":"bad"}`}>{msg}</div>}<button className="btn btn-primary">Guardar cambios</button></form></div>}
  {mode==="pin"&&selected&&<div className="stack"><div className="row"><strong>PIN de {selected.last_name}, {selected.first_name}</strong><div className="spacer"/><button className="btn btn-secondary" onClick={()=>setMode("none")}>Cerrar</button></div><div className="notice info">El administrador no puede ver el PIN actual. Solo puede asignar uno nuevo. Los cambios quedan registrados en auditoría sin guardar el valor del PIN.</div><form className="stack" onSubmit={savePin}><div><label className="label">Nuevo PIN (4 a 8 dígitos)</label><input className="input" inputMode="numeric" pattern="[0-9]{4,8}" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} required/></div><label className="row"><input type="checkbox" checked={forcePinChange} onChange={e=>setForcePinChange(e.target.checked)}/><span>Forzar cambio de PIN en el próximo ingreso</span></label>{selected.pin_changed_at&&<div className="muted">Último cambio: {new Date(selected.pin_changed_at).toLocaleString("es-AR")} · Origen: {selected.pin_change_source==="EMPLOYEE"?"empleado":"administración"} · Reseteos administrativos: {Number(selected.pin_reset_count||0)}</div>}{msg&&<div className={`notice ${msg.includes("correctamente")?"good":"bad"}`}>{msg}</div>}<button className="btn btn-primary">Guardar PIN</button></form></div>}
  {mode==="bulkpin"&&<div className="stack"><div className="row"><strong>Generación masiva de PIN provisorios</strong><div className="spacer"/><button className="btn btn-secondary" onClick={()=>setMode("none")}>Cerrar</button></div><div className="notice info">Solo se generarán PIN para agentes activos que todavía no tengan uno configurado. No se sobrescribirá ningún PIN existente. Cada PIN provisorio vence a los 7 días y obliga al agente a elegir un PIN personal en el primer uso.</div>{!bulkPins.length&&<button className="btn btn-primary" disabled={bulkLoading} onClick={generateBulkPins}>{bulkLoading?"Generando...":"Generar PIN pendientes"}</button>}{bulkMsg&&<div className={`notice ${bulkPins.length?"good":"info"}`}>{bulkMsg}</div>}{bulkPins.length>0&&<><div className="row"><button className="btn btn-primary" onClick={downloadBulkPins}>Descargar listado CSV</button><span className="muted">Guardalo en un lugar seguro y distribuí cada PIN únicamente a su titular.</span></div><div className="table-wrap"><table><thead><tr><th>Apellido y nombre</th><th>DNI</th><th>PIN provisorio</th><th>Vence</th></tr></thead><tbody>{bulkPins.map(x=><tr key={x.id}><td>{x.lastName}, {x.firstName}</td><td>{x.dni}</td><td><strong>{x.pin}</strong></td><td>{new Date(x.expiresAt).toLocaleDateString("es-AR")}</td></tr>)}</tbody></table></div></>}</div>}
  {mode==="device"&&selected&&<div className="stack"><div className="row"><strong>Dispositivo de {selected.last_name}, {selected.first_name}</strong><div className="spacer"/><button className="btn btn-secondary" onClick={()=>setMode("none")}>Cerrar</button></div><div className={`notice ${Number(selected.active_devices)>0?"good":"info"}`}>{Number(selected.active_devices)>0?`Tiene un dispositivo autorizado${selected.device_last_seen?` · último uso ${selected.device_last_seen}`:""}.`:"Todavía no vinculó un dispositivo. La primera marcación válida vinculará automáticamente su celular."}</div>{Number(selected.active_devices)>0&&<button className="btn btn-danger" onClick={revokeDevice}>Desvincular dispositivo</button>}{msg&&<div className={`notice ${msg.includes("correctamente")?"good":"bad"}`}>{msg}</div>}</div>}
  </div></div>}
  <div className="card"><label className="label" htmlFor="search">Buscar agente</label><input id="search" className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Apellido, nombre o DNI"/></div>
  <div className="card table-wrap"><table><thead><tr><th>Agente</th><th>Situación</th><th>Horario semanal</th><th>PIN</th><th>Dispositivo</th><th>Acciones</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id} style={{opacity:e.active?1:.55}}><td><strong>{e.last_name}, {e.first_name}</strong><div className="muted">DNI {e.dni} · {e.active?"Activo":"Inactivo"}</div></td><td>{e.employment}{e.seniority_date&&<div className="muted">Antigüedad reconocida desde {new Date(e.seniority_date+"T00:00:00").toLocaleDateString("es-AR")}</div>}</td><td>{e.schedules.length?e.schedules.map(s=><div key={s.weekday}>{dayNames[s.weekday]} {String(s.start_time).slice(0,5)}–{String(s.end_time).slice(0,5)}</div>):<span className="muted">Sin horario</span>}</td><td><span className={`badge ${e.pin_configured?"good":"warn"}`}>{e.pin_configured?"Configurado":"Pendiente"}</span>{e.force_pin_change&&<div><span className="badge warn">Cambio obligatorio</span></div>}{e.pin_changed_at&&<div className="muted">Último cambio {new Date(e.pin_changed_at).toLocaleDateString("es-AR")}</div>}{e.force_pin_change&&e.temporary_pin_expires_at&&<div className="muted">PIN provisorio vence {new Date(e.temporary_pin_expires_at).toLocaleDateString("es-AR")}</div>}</td><td><span className={`badge ${Number(e.active_devices)>0?"good":"info"}`}>{Number(e.active_devices)>0?"Vinculado":"Sin vincular"}</span>{e.device_last_seen&&<div className="muted">Último uso {e.device_last_seen}</div>}</td><td><div className="row"><button className="btn btn-secondary" onClick={()=>openEdit(e)}>Editar</button><button className="btn btn-secondary" onClick={()=>{setSelected(e);setMode("pin");setMsg("");setPin("");setForcePinChange(true);}}>PIN</button><button className="btn btn-secondary" onClick={()=>{setSelected(e);setMode("device");setMsg("");}}>Dispositivo</button></div></td></tr>)}</tbody></table></div>

 </div>;
}
